# 因为Darc太懒了, 所以请对每个配置项添加双引号
# GetConfig返回值的全部为string哦
# 如果不加双引号就读取不到了
version: "1" # 配置文件版本号, 生产环境请勿修改

# 用于鉴权的密钥
# 可以使用 Python3.6+ 生成密钥
# import random, string
# ''.join(random.choices(string.ascii_letters + string.digits, k=256))
SECRET: "wM90fjrlbusm1tlmrJRoKK70ZrI3lyAEL4p24z0gZnbABDoSUZlRs6ZWdrPbYmI54NeShji5sBzHKVK22AU0vyggJlGjOYpYK0PJcKLqaQhp16U0g9MldkJZKQJ6mOtlevZUg5jkgfHGBmbrlxiIwsMrjnuIVpCkabAVXRPR0CEkWbiL312sJIIciHPtgypYNkT2ZsFSFeNvgOuAljaGq4sMzkTEWjiBIUVPLhGXq2HliTH5SCYFnTTJ42u3gHVp"

# RABBITMQ
RMQ_URL: "amqp://admin:admin@192.168.50.111:5672/admin"
RMQ_QNAME: "anwser_submit"
